version: '2'
services:
  app:
    build: laravel
    depends_on: 
      - db
  db:
    build: mysql
    environment: 
      MYSQL_ROOT_PASSWORD: root
  web:
    build: nginx
    ports: 
      - 80:80
      volumes: 
        - ./nginx/log:/var/log/nginx
      volumes_from: 
        - app
      depends_on: 
        - app